### ISSUE TITLE
Gossamer installation [file INSTALL cannot copy file]

### ISSUE THREAD

**Issue by sushang-thu** [data61/gossamer#27]
Hi,

I ran into an error when installing gossamer onto Ubuntu.
It showed in the

 "
make install
"
step

CMake Error at src/cmake_install.cmake:47 (file):
  file INSTALL cannot copy file "/home/shang/gossamer/build/src/goss" to
  "/usr/local/bin/goss".
Call Stack (most recent call first):
  cmake_install.cmake:42 (include)
Makefile:128: recipe for target 'install' failed
make: *** [install] Error 1

any suggestions?
I am running a WSL Ubuntu on Windows 10.  I first installed all the recommended prerequisites and then git clone gossamer.
---
cd gossamer
mkdir build
cd build
cmake ..
make
make test
make install
---

Thanks very much!

**Comment by beyondpie** [comment]
@sushang-thu  if you solve this issue, you could close it.

**Comment by Deguerre** [comment]
You may be the first to try to build Gossamer on WSL, so thanks for trying it out!

I'm not very familiar with WSL, but my first impression is that either /usr/local/bin doesn't exist, or the permissions are not set correctly.

Can you try `sudo make install` instead of `make install`?

**Comment by beyondpie** [comment]
Hi, @Deguerre 

Shang has installed the program. and we don't move the code, which might need a root dir (we haven't tested the existence of /usr/local/bin).

Since most of the users would install the program without root permission,  it might be better if  you can support the non-root version of this program.  According to our experience,  not using sudo and just simply following your cmakefile is enough (except the movement of the executable file finally to /usr/local/bin).

Thank you very much for your work!

Songpeng

**Comment by sushang-thu** [comment]
Thanks all,

I am now running the xenome index command on WSL (Ubuntu). 
After several hours, 23 idx files were created but it seems that the command is still running.
![image](https://user-images.githubusercontent.com/59237736/78680786-ee44f180-78b9-11ea-8ab2-a4f370139f8e.png)

I will close this issue anyway.

**Comment by Deguerre** [comment]
Thanks for this. Two comments:

1. You can install xenome in a different directory telling CMake where to install:

`cmake -DCMAKE_INSTALL_PREFIX=~/.local/or/wherever/you/want etc etc`

2. There is an outstanding bug in the released version of xenome that under some circumstances there's an infinite loop in index generation. You can try -T 1 (IIRC, -T 8 still works fine for queries, just not index generation).
